// <auto-generated />
using System;
using LicitApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicitApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicitApp.Api.Domain.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.ToTable("materiales", (string)null);
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OfertaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SolicitudId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Oferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CorralonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorralonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("CorralonRating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBestPrice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFastDelivery")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ShippingPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ShippingType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorralonId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("SolicitudId", "Status");

                    b.ToTable("ofertas", (string)null);
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConstructorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConstructorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CorralonesNotifiedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OfertasCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WinningOfferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeliveryZone", "Status");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("LicitApp.Api.Domain.User", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PushToken")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.HasIndex("Role");

                    b.HasIndex("Zone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Material", b =>
                {
                    b.HasOne("LicitApp.Api.Domain.Solicitud", "Solicitud")
                        .WithMany("Materiales")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Notification", b =>
                {
                    b.HasOne("LicitApp.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Oferta", b =>
                {
                    b.HasOne("LicitApp.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CorralonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LicitApp.Api.Domain.Solicitud", "Solicitud")
                        .WithMany("Ofertas")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Solicitud", b =>
                {
                    b.HasOne("LicitApp.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LicitApp.Api.Domain.User", b =>
                {
                    b.OwnsOne("LicitApp.Api.Domain.UserStats", "Stats", b1 =>
                        {
                            b1.Property<string>("UserUid")
                                .HasColumnType("text");

                            b1.Property<int>("TotalCierres")
                                .HasColumnType("integer")
                                .HasColumnName("stats_total_cierres");

                            b1.Property<int>("TotalLicitaciones")
                                .HasColumnType("integer")
                                .HasColumnName("stats_total_licitaciones");

                            b1.Property<int>("TotalOfertas")
                                .HasColumnType("integer")
                                .HasColumnName("stats_total_ofertas");

                            b1.HasKey("UserUid");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserUid");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("LicitApp.Api.Domain.Solicitud", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Ofertas");
                });
#pragma warning restore 612, 618
        }
    }
}
